apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-service-app
  labels:
   app: metadata
spec:
  replicas: 2
  selector:
    matchLabels:
          app: metadata
  template:
    metadata:
      labels:
        app: metadata
    spec:
      containers:
      - name: metadata
        image: metadata-service:1.0
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: metadata-service
  labels:
      app: metadata
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: metadata
  type: NodePort